data_ingestion:
  data_source: data/external/food_delivery.csv
  test_size: 0.2
  random_state: 42

data_preprocessing:
  raw_data_path: data/raw
  processed_data_path: data/interim

feature_engineering:
  interim_data_path: data/interim
  processed_data_path: data/processed

model_training:
  n_estimators: 200
  max_depth: 10
  learning_rate: 0.05
  random_state: 42

model_evaluation:
  model_name: swiggy_delivery_time_model
  stage: staging
