name: CICD Pipeline

on: push

jobs:
  model-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pipeline
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          dvc repro


      - name: Install test dependencies
        run: |
          pip install pytest

      - name: Model performance
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          pytest scripts/test_model_performance.py

      - name : Promote model
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python scripts/promote_model.py   

      - name: Build Docker image for docker hub 
        if: success()
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/swiggy_delivery:v2 .  

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
         username: ${{ secrets.DOCKER_HUB_USERNAME }}
         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker Image
        run: |
         docker push ${{ secrets.DOCKER_HUB_USERNAME }}/swiggy_delivery:v2

      # 5. Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            # Login to Docker Hub
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | \
            docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            # Pull latest image
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/swiggy_delivery:v2

            # Stop old container
            docker stop swiggy_delivery || true

            # Remove old container
            docker rm swiggy_delivery || true

            # Run new container
            docker run -d \
              --name swiggy_delivery \
              -p 8000:8000 \
              --restart unless-stopped \
              ${{ secrets.DOCKER_HUB_USERNAME }}/swiggy_delivery:v2

            # Remove unused images
            docker image prune -f